### ISSUE TITLE
bad checksum

### ISSUE THREAD

**Issue by jasonzhao77** [HybridELEC/hepacker#4]
我在输入命令后出现如下问题：
python hepacker.py --android /home/jason/hybrid/HK1BOX9.0.img --ce-tar /home/jason/hybrid/CoreELEC.21.1.1.img --ce-dtb sm1_s905x3_4g_1gbit --ce-storage 5G --ee-tar /home/jason/hybrid/EmuELEC.4.7.img --ee-dtb sm1_s905x3_4g_1gbit --ee-storage 45G --output hk1_hybrid.img
---------------------------------------------------------------------------------------------
Unpacked image '/home/jason/hybrid/HK1BOX9.0.img' to 'building/everything'
Traceback (most recent call last):
  File "/home/jason/hepacker/hepacker.py", line 364, in <module>
    main()
  File "/home/jason/hepacker/hepacker.py", line 340, in main
    ce_options.build("ce", building)
  File "/home/jason/hepacker/hepacker.py", line 232, in build
    self.build_tar(UpgradeTar(name, self.tar, self.dtb), building)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jason/hepacker/hepacker.py", line 65, in __init__
    tar = tarfile.TarFile(path, 'r', format = tarfile.GNU_FORMAT)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/tarfile.py", line 1745, in __init__
    self.firstmember = self.next()
                       ^^^^^^^^^^^
  File "/usr/lib/python3.12/tarfile.py", line 2655, in next
    raise ReadError(str(e)) from None
tarfile.ReadError: bad checksum

这是固件本身有问题，还是我的python哪里有问题？系统是archlinux20240801，三个固件都是官方的，安卓是u255.HK1_BOX_CN_pure_1000M_9.0.2021.04.28.17.17，我试过SLIMBOX的，也出现这个问题。命令我改用python3，也是这样。

**Comment by 7Ji** [comment]
ce-tar ee-tar

**Comment by jasonzhao77** [comment]
感谢大神回复！之前这个问题因为紧跟着解包安卓固件出现，我一直以为是安卓固件的问题，没想到是其他两个固件的格式问题，多谢大神提醒。不过改了tar，似乎还是有问题。

python hepacker.py --android /home/jason/hybrid/HK1BOX9.0.img --ce-tar /home/jason/hybrid/CoreELEC.21.1.1.tar --ce-dtb sm1_s905x3_4g_1gbit --ce-storage 5G --ee-tar /home/jason/hybrid/EmuELEC.4.7.tar --ee-dtb sm1_s905x3_4g_1gbit --ee-storage 45G --output hk1_hybrid.img

Unpacked image '/home/jason/hybrid/HK1BOX9.0.img' to 'building/everything'
Traceback (most recent call last):
  File "/home/jason/hepacker/hepacker.py", line 364, in <module>
    main()
  File "/home/jason/hepacker/hepacker.py", line 340, in main
    ce_options.build("ce", building)
  File "/home/jason/hepacker/hepacker.py", line 232, in build
    self.build_tar(UpgradeTar(name, self.tar, self.dtb), building)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jason/hepacker/hepacker.py", line 70, in __init__
    tar.getmember(f"{target}/KERNEL"),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/tarfile.py", line 2018, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'CoreELEC.21.1.1.img/target/KERNEL' not found"

我是固件img直接转的tar，是不是这个tar里还要放别的文件？dtb文件？还要别的？我是刚接触linux的小白，看了hepacker.py的源码还是看不懂，烦劳大神再指点下。

**Comment by 7Ji** [comment]
你直接改后缀名多少有点抽象了。老老实实到对应项目下载页去下升级用的.tar文件，不要下.img.gz解压。

**Comment by jasonzhao77** [comment]
原来如此，我潜意识里认为三合一的固件应该都是独立可装的，虽然看到了update tar，但以为这个说的是直接安装的固件，走了弯路，多谢大神指正！现在三合一已经弄好，但在烧录的时候，又出现问题了，到98%出现烧录分区 bootloader/检验分区/命令结果返回错误。试了几次都这样，单独选擦除flash所有不行；同时选擦除flash和bootloader也不行。

[15:27:44 349][HUB4-1][Inf]-------------Download bootloader.PARTITION-----------
[15:27:44 349][HUB4-1][Inf]--0-7-0-16
[15:27:44 349][HUB4-1][Inf]--download store bootloader normal 1286000
[15:27:44 349][HUB4-1][Inf]--Send download command success
[15:27:44 364][HUB4-1][Inf]--Read command status success
[15:27:44 614][HUB4-1][Inf]--Transfer complete
[15:27:44 614][HUB4-1][Inf]--Send download get_status command succeed
[15:27:44 630][HUB4-1][Inf]--get_status success
[15:27:44 630][HUB4-1][Inf]--verify ?
[15:27:44 630][HUB4-1][Inf]--Send verify cmd succeed
[15:27:44 630][HUB4-1][Inf]--ItemSize: 1286000
[15:27:44 630][HUB4-1][Err]--failed:need 3 args

[15:27:44 630][HUB4-1][Err]--[0x30405004]UBOOT/烧录分区 bootloader/检验分区/命令结果返回错误
[15:27:44 630][HUB4-1][Inf]--Close device handle 0x00000ed8

我改用单安卓包刷，是成功的，但三合一的就是不行。图中成功的都是单安卓包，三合一都失败。
![无标题](https://github.com/user-attachments/assets/1d300098-5358-4062-81bb-7e5fcdc59635)

这是解包后的文件清单
![无标题2](https://github.com/user-attachments/assets/5058b83f-8674-4c81-a1d7-b2261cc6df48)

**Comment by 7Ji** [comment]
更新测试

https://github.com/7Ji/ampack/commit/46066067b2b06c387df14243e301742644aa77a1

另外

> 这是解包后的文件清单

不要用Win下解包工具给我看截图，解包模块没有问题，看这个没有参考意义

**Comment by jasonzhao77** [comment]
多谢大神回复！烧录这个问题我后来解决了，我看到你HK1三合一包链接里有提到改了boot and recovery partition，所以我提取你包里的boot.PARTITION替换到了我自己的包，居然让我刷成功了。再次感谢！
